version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps:"
    groups:
      all-go-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2/internal/*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci:"
    groups:
      actions:
        patterns:
          - "*"
