version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    commit-message:
      prefix: "deps"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    commit-message:
      prefix: "ci"
